version: '3.7'

services:

  mobilebw:
    container_name: mobilebw-container
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    